apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: gagan2104/cicd_poc:fc7874d
        ports:
        - containerPort: 8080

        
